language: php

php:
    - 5.5
    - 5.6

include:
    - php: 5.5
      env: dependencies=lowest

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

